# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_motor_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('motor', models.CharField(blank=True, max_length=60, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Motos',
                'verbose_name': 'Moto',
            },
        ),
    ]
